import { Photo } from './photo';
import { Account } from './account';
import { Address } from './address';
import { Order } from './order';

export interface Customer {
  paymentMethods: any[];
  reviews: any[];
  ratings: any[];
  carts: any[];
  wishlists: any[];
  subscriptions: any[];
  feedbacks: any[];
  complaints: any[];
  refunds: any[];
  reports: any[];
  chats: any[];
  conversations: any[];
  messages: any[];
  notifications: any[];
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  passwordUpdate: any;
  age: any;
  dateOfBirth: any;
  lastActiveAt: any;
  gender: string;
  photos: Photo[];
  addressId: string;
  address: Address;
  orders: Order[];
  accounts: Account[];
  currentAccount: string;
  isDomainResponsible: any;
  token: string;
  refreshTokens: any[];
  id: string;
  createdAt: string;
  updatedAt: string;
  isDeleted: boolean;
}
